### ISSUE TITLE
how can I do set setCurrentItem function?

### ISSUE THREAD

**Issue by S-Masoud-Emamian** [kmshack/Android-ParallaxHeaderViewPager#22]
Hi

how can I do set setCurrentItem function?

after below code I get some errors :

     mViewPager.setCurrentItem(3);

errors :

at com.kmshack.newsstand.MainActivity.onPageSelected(MainActivity.java:145)
            at com.astuetz.PagerSlidingTabStrip$PageListener.onPageSelected(PagerSlidingTabStrip.java:387)
            at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:548)
            at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:514)
            at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:495)
            at com.kmshack.newsstand.MainActivity.onCreate(MainActivity.java:126)//mViewPager.setCurrentItem(3);

**Comment by S-Masoud-Emamian** [comment]
Solved : 
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                mViewPager.setCurrentItem(3);
            }
        },500);
