### ISSUE TITLE
AppCompat v21 support?

### ISSUE THREAD

**Issue by nitrico** [kmshack/Android-ParallaxHeaderViewPager#9]
Is there any way to get it working with the new appcompat support library? They introduced many changes on it and I don't find how to solve the problem of getActionBarIconView() always returning null.

**Comment by ed-george** [comment]
Thank you @nitrico, I can also confirm that this work around does rectify the issues with AppCompat v21

**Comment by cjgehinscott** [comment]
I can confirm that this fix does not work anymore...

07-07 09:56:15.633    3430-3430/com.bah.is.esd.zoneapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.bah.is.esd.zoneapp, PID: 3430
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bah.is.esd.zoneapp/com.bah.is.esd.zoneapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setAlpha(float)' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setAlpha(float)' on a null object reference
            at com.bah.is.esd.nineoldandroids.view.ViewHelper$Honeycomb.setAlpha(ViewHelper.java:185)
            at com.bah.is.esd.nineoldandroids.view.ViewHelper.setAlpha(ViewHelper.java:19)
            at com.bah.is.esd.zoneapp.MainActivity.layoutView(MainActivity.java:525)
            at com.bah.is.esd.zoneapp.MainActivity.onCreate(MainActivity.java:135)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by cjgehinscott** [comment]
Make your theme a child of Theme.AppCompat.Light.NoActionBar like so:

<style name="NoActionBarTheme" parent="Theme.AppCompat.Light.NoActionBar">
     ...
</style>
